name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        setup:
        - { profile: 'mongodb-v3,mongo-driver-3.7', docker_db_version: 3.6.23 }
        - { profile: 'mongodb-v3,mongo-driver-3.12', docker_db_version: 3.6.23 }
        - { profile: 'mongodb-v3,mongo-driver-3.12', docker_db_version: 4.2.19 }

    steps:
    - name: get source code
      uses: actions/checkout@v2
    - name: setup cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build with maven
      run: mvn -B clean install -P ${{ matrix.setup.profile }} -Dmongodb.container.version=${{ matrix.setup.docker_db_version }}
